name: Trivy Scanner - Container Images

on:
  schedule:
    - cron: '0 6 * * 1' # Weekly on Monday at 6am UTC
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  build-matrix:
    # TODO: Uncomment before merging to main
    # if: ${{ github.repository == 'awslabs/mountpoint-s3-csi-driver' }}
    runs-on: ubuntu-latest
    outputs:
      images: ${{ steps.set-matrix.outputs.result }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - id: set-matrix
        uses: mikefarah/yq@v4
        with:
          cmd: >
            yq '[
              (.image.repository + ":" + .image.tag),
              (.sidecars.nodeDriverRegistrar.image.repository + ":" + .sidecars.nodeDriverRegistrar.image.tag),
              (.sidecars.livenessProbe.image.repository + ":" + .sidecars.livenessProbe.image.tag),
              .experimental.headroomPodImage
            ] | . style="flow"' charts/aws-mountpoint-s3-csi-driver/values.yaml

  trivy-scan:
    needs: build-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ${{ fromJson(needs.build-matrix.outputs.images) }}
    steps:
      - name: Pull container image
        run: docker pull ${{ matrix.image }}

      - name: Scan container image
        uses: aquasecurity/trivy-action@0.35.0
        env:
          TRIVY_DB_REPOSITORY: ghcr.io/aquasecurity/trivy-db,public.ecr.aws/aquasecurity/trivy-db
        with:
          image-ref: '${{ matrix.image }}'
          output: 'results.sarif'
          format: 'sarif'
          ignore-unfixed: true
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: 'results.sarif'
